;;; +org-caldav.el --- org-caldav daemon-side helpers -*- lexical-binding: t; -*-
;;
;;; Commentary:
;;
;; Daemon-side helpers that drive `org-caldav-sync' in a subprocess against a
;; local davmail bridge on 127.0.0.32:1080. The `use-package!' block for the
;; org-caldav package itself lives in config.el; this file holds the
;; reachability probe, batch-script generator, sync subprocess plumbing,
;; modeline error indicator, periodic timer, and the daemon-init hook.
;;
;;; Code:

(defun +org-caldav-davmail-up-p ()
  "Return non-nil if davmail's CalDAV port is reachable on 127.0.0.32:1080."
  (condition-case nil
      (let ((proc (open-network-stream "davmail-probe" nil
                                       "127.0.0.32" 1080
                                       :type 'plain :nowait nil)))
        (delete-process proc)
        t)
    (error nil)))

(defvar +org-caldav-last-error nil
  "Most recent org-caldav sync error, or nil if last sync succeeded.")

(defvar +org-caldav-sync-process nil
  "Active subprocess running org-caldav-sync, or nil.")

(defvar +org-caldav-sync-timer nil
  "Repeating timer running `+org-caldav-sync-quietly', or nil.")

(defvar +org-caldav-batch-script
  (expand-file-name "org-caldav-batch.el"
                    (or (getenv "XDG_RUNTIME_DIR") temporary-file-directory))
  "Path to the auto-generated batch script run by `+org-caldav-sync-quietly'.
Lives under XDG_RUNTIME_DIR (tmpfs, per-user, mode 0700) or
`temporary-file-directory' as a fallback. Contains a base64-encoded
credential, so it should never persist to disk.")

(defun +org-caldav--encoded-davmail-credential ()
  "Return the base64 of \"user:pass\" for davmail, fetched via auth-source.
Runs on the main thread where auth-source can do gpg/rbw safely.
Returns nil if no credential is available."
  (when-let* ((entry (car (auth-source-search :host "127.0.0.32"
                                              :port "1080" :max 1)))
              (user (plist-get entry :user))
              (secret (plist-get entry :secret))
              (pass (if (functionp secret) (funcall secret) secret)))
    (base64-encode-string
     (encode-coding-string (format "%s:%s" user pass) 'utf-8)
     t)))

(defun +org-caldav-write-batch-script ()
  "Generate the self-contained batch script that performs a sync.
Bakes in the daemon's load-path, calendar config, and a pre-encoded
url-http basic-auth credential keyed by the davmail realm so the
subprocess never needs to consult auth-source. The script is written
mode 0600 because it contains a base64-encoded password."
  (require 'org-caldav)
  (let ((cred (+org-caldav--encoded-davmail-credential)))
    (unless cred
      (error "[org-caldav] auth-source did not return a credential for 127.0.0.32:1080"))
    (with-temp-file +org-caldav-batch-script
      (let ((print-length nil)
            (print-level nil)
            (print-quoted t))
        (insert ";;; org-caldav-batch.el -*- lexical-binding: t -*-\n")
        (insert ";; AUTO-GENERATED. Regenerated by the daemon at startup.\n")
        (insert ";; Contains a base64-encoded credential; mode 0600.\n\n")
        (prin1 `(setq load-path ',load-path) (current-buffer)) (insert "\n")
        (prin1 `(progn
                  (require 'url-auth)
                  (require 'org)
                  (require 'org-id)
                  (require 'org-caldav)
                  (setq url-http-real-basic-auth-storage '(("127.0.0.32:1080" ("DavMail Gateway" . ,cred)))
                        org-caldav-calendars ',org-caldav-calendars
                        org-caldav-save-directory ,org-caldav-save-directory
                        org-caldav-backup-file ,org-caldav-backup-file
                        org-caldav-uuid-extension ,org-caldav-uuid-extension
                        org-caldav-show-sync-results nil
                        org-caldav-delete-org-entries 'never
                        org-icalendar-timezone ,org-icalendar-timezone
                        org-id-locations-file ,org-id-locations-file
                        org-id-track-globally t)
                  (advice-add 'org-caldav-sync-state-filename :override
                              (lambda (id)
                                (expand-file-name
                                 (concat "org-caldav-"
                                         (substring
                                          (md5 (concat (or org-caldav-url "") "/" id))
                                          1 8)
                                         ".el")
                                 org-caldav-save-directory)))
                  (org-caldav-sync)
                  (kill-emacs 0))
               (current-buffer))))
    (set-file-modes +org-caldav-batch-script #o600)))

(defun +org-caldav--sentinel (proc _event)
  "Update last-error / modeline when the sync subprocess exits."
  (when (memq (process-status proc) '(exit signal))
    (let ((exit (process-exit-status proc))
          (output (with-current-buffer (process-buffer proc)
                    (string-trim (buffer-string)))))
      (kill-buffer (process-buffer proc))
      (setq +org-caldav-sync-process nil)
      (if (zerop exit)
          (setq +org-caldav-last-error nil)
        (setq +org-caldav-last-error
              (cons 'subprocess-failure
                    (format "exit=%s output=%s" exit output)))
        (let ((inhibit-message t))
          (message "[org-caldav] subprocess sync failed (exit %s): %s"
                   exit output)))
      (force-mode-line-update t))))

(defun +org-caldav-sync-quietly ()
  "Run `org-caldav-sync' in a subprocess when davmail is up.
Skips if a previous sync subprocess is still running. Errors are
recorded in `+org-caldav-last-error', logged to *Messages* (no echo),
and surfaced as a modeline warning."
  (when (and (+org-caldav-davmail-up-p)
             (file-exists-p +org-caldav-batch-script)
             (not (and +org-caldav-sync-process
                       (process-live-p +org-caldav-sync-process))))
    (setq +org-caldav-sync-process
          (make-process
           :name "org-caldav-batch"
           :buffer (generate-new-buffer " *org-caldav-batch-output*")
           :command (list (or (executable-find "emacs") "emacs")
                          "-Q" "--batch"
                          "-l" +org-caldav-batch-script)
           :noquery t
           :sentinel #'+org-caldav--sentinel))))

(defun +org-caldav--reset-sync-timer ()
  "Cancel any existing periodic sync timer and schedule a fresh one."
  (when (timerp +org-caldav-sync-timer)
    (cancel-timer +org-caldav-sync-timer))
  (setq +org-caldav-sync-timer
        (run-with-timer 60 (* 15 60) #'+org-caldav-sync-quietly)))

(defun +org-caldav-restart-sync ()
  "Clear the caldav modeline warning and trigger a fresh sync.
Kills any stuck subprocess, resets `+org-caldav-last-error',
regenerates the batch script (so credential or config changes
take effect), cancels and reschedules the periodic sync timer,
and calls `+org-caldav-sync-quietly'. No-ops with a message
when davmail is not reachable."
  (interactive)
  (when (and +org-caldav-sync-process (process-live-p +org-caldav-sync-process))
    (delete-process +org-caldav-sync-process))
  (setq +org-caldav-sync-process nil
        +org-caldav-last-error nil)
  (force-mode-line-update t)
  (if (not (+org-caldav-davmail-up-p))
      (message "[org-caldav] davmail (127.0.0.32:1080) not reachable; skipping")
    (+org-caldav-write-batch-script)
    (+org-caldav--reset-sync-timer)
    (+org-caldav-sync-quietly)))

(add-to-list
 'global-mode-string
 '(:eval (when (bound-and-true-p +org-caldav-last-error)
           (propertize " ⚠ caldav"
                       'face 'warning
                       'help-echo
                       (format "org-caldav last sync error: %s"
                               (error-message-string +org-caldav-last-error)))))
 t)

(defvar +org-caldav--bootstrap-timer nil
  "Timer probing for davmail at startup, or nil once we've bootstrapped.")

(defun +org-caldav--bootstrap-poll ()
  "Bootstrap the periodic sync once davmail is reachable.
Re-arms a 1s timer on each failure so a daemon started before davmail
can recover automatically when the bridge comes up. Avoids the
auth-source lookup while davmail is unreachable. A plain (non-idle)
timer is used because the daemon and davmail are both user services
that often race at login; an idle timer wouldn't re-fire while the
daemon sits idle waiting for davmail."
  (setq +org-caldav--bootstrap-timer nil)
  (if (+org-caldav-davmail-up-p)
      (progn
        (+org-caldav-write-batch-script)
        (+org-caldav--reset-sync-timer))
    (setq +org-caldav--bootstrap-timer
          (run-with-timer 1 nil #'+org-caldav--bootstrap-poll))))

;; Only the daemon runs the periodic sync; secondary Emacs instances would
;; race on state files. Cancel any prior bootstrap (e.g. on doom/reload)
;; before scheduling a fresh one, and skip if a sync timer is already live.
(when (timerp +org-caldav--bootstrap-timer)
  (cancel-timer +org-caldav--bootstrap-timer))
(setq +org-caldav--bootstrap-timer nil)
(when (and (daemonp)
           (not (and +org-caldav-sync-timer
                     (memq +org-caldav-sync-timer timer-list))))
  (setq +org-caldav--bootstrap-timer
        (run-with-timer 1 nil #'+org-caldav--bootstrap-poll)))
